set number	"" Show line numbers
set linebreak	"" Break lines at word (requires Wrap lines)
set showbreak=+++	"" Wrap-broken line prefix
set textwidth=100	"" Line wrap (number of cols)
set showmatch	"" Highlight matching brace
set visualbell	"" Use visual bell (no beeping)
 
set hlsearch	"" Highlight all search results
set smartcase	"" Enable smart-case search
set ignorecase	"" Always case-insensitive
set incsearch	"" Searches for strings incrementally
 
set autoindent	"" Auto-indent new lines
set cindent	"" Use 'C' style program indenting
set smartindent	"" Enable smart-indent
set smarttab	"" Enable smart-tabs
set softtabstop=8	"" Number of spaces per Tab
 
"""" Advanced
set ruler	"" Show row and column ruler information
 
set undolevels=1000	"" Number of undo levels
set backspace=indent,eol,start	"" Backspace behaviour
 
set tabstop=8
set softtabstop=8
set shiftwidth=8
set noexpandtab 
"""" Generated by VimConfig.com


""" VIM-LATEX
filetype plugin on
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
""""
